[workspace]

members = [
    "gen",
    "gltf2",
    "scene",
    "com_ptr_util",
    "renderer",
    "frame_factory",
    #
    # "sample",
    "from_jsonschema",
    "from_cpp_header",
]
