[package]
name = "from_cpp_header"
version = "0.1.0"
authors = ["ousttrue <ousttrue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang-sys = { version="1.2.0", features=["clang_3_8", "clang_3_9"] }
